
server:
  port: 8080

stratz:
  token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJodHRwczovL3N0ZWFtY29tbXVuaXR5LmNvbS9vcGVuaWQvaWQvNzY1NjExOTgwNDk1MDEwOTEiLCJ1bmlxdWVfbmFtZSI6Iue_vOOCkuOBj-OBoOOBleOBhCIsIlN1YmplY3QiOiIwY2QyZDkxYy05ZmY3LTRhNmQtYjAwYy1hMTNkYjhjMGI3MjciLCJTdGVhbUlkIjoiODkyMzUzNjMiLCJuYmYiOjE2NDY3NDM2MDksImV4cCI6MTY3ODI3OTYwOSwiaWF0IjoxNjQ2NzQzNjA5LCJpc3MiOiJodHRwczovL2FwaS5zdHJhdHouY29tIn0.9QATTNOU7O3fjviizJm662XwZ8dTc58JT-74QvuOhJ4